### ISSUE TITLE
Issues with authenticating

### ISSUE THREAD

**Issue by zkapfumvuti** [biblibre/omeka-s-module-Ldap#10]
Hi @jajm Im having issues with authenticating with LDAP, im on Omeka-S 3.2.1 and using php 8.1.

The error message I get are credentials are invalid.

Ldap: 0x1: Failed to retrieve DN for account: xxxxxxx@uct.ac.za [Failed to connect to LDAP server: xxxxx.uct.ac.za:001]

Kindly advise if you are aware of any issues.

**Comment by jajm** [comment]
It looks like Omeka cannot contact your LDAP server. So either the URL is wrong, or you have network issues.

Also be aware that Omeka S 3.2.1 is not fully compatible with PHP 8.1. I'd recommend downgrading to PHP 8.0

**Comment by zkapfumvuti** [comment]
Thanks Julian, let me downgrade the PHP and I’ll let you know how I get on.

**Comment by zkapfumvuti** [comment]
I installed a fresh Omeka S 3.2.1 on Ubuntu 18 testing (PHP 8.0), and when enabling the Ldap module I also got a 500 error page. If I remove the LDAP module from the modules folder, the problem goes away.

**Comment by jajm** [comment]
Do you have any related error messages in `logs/application.log` ?

**Comment by zkapfumvuti** [comment]
No unfortunately not, apart from this Ldap: 0x1: Failed to retrieve DN for account: [xxxxxxx@uct.ac.za](mailto:xxxxxxx@uct.ac.za) [Failed to connect to LDAP server: xxxxx.uct.ac.za:001]

**Comment by jajm** [comment]
Just did a fresh install too (Omeka S 3.2.1, ubuntu 21.10, PHP 8.0) with Ldap 0.3.2 and I see no problems... :-/

Can you try to replace "production" by "development" in `.htaccess` file and see if an error message shows up ?

**Comment by zkapfumvuti** [comment]
Hi Julian, im on Ubuntu 18.04, running PHP 8.0.20 (cli) (built: Jun 10 2022 13:11:14) ( NTS ), and Omeka S 3.2.1 and trying to install Ldap 0.3.2 by extrating from zip file and placing in modules folder I get 2 error message;



( ! ) Warning: Uncaught Error in exception handling during call to Error::__toString() in /data/www/omeka-s/vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Connection.php on line 0
--


<br class="Apple-interchange-newline">


And when i try via composer not using root user, I get this;

/data/www/omeka-s/modules/Ldap$ composer install --no-dev
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Cannot create cache directory /home/01466101/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/01466101/.composer/cache/files/, or directory is not writable. Proceeding without cache

In ArrayLoader.php line 44:

  Unknown package has no name defined ([{"name":"laminas\/laminas-ldap","version":"2.10.3","version_normalized":"2.10.3.0","source":{"type":
  "git","url":"https:\/\/github.com\/laminas\/laminas-ldap.git","reference":"649fae8982149b93071c4a7d56f2c4efeed51aa8"},"dist":{"type":"zip"
  ,"url":"https:\/\/api.github.com\/repos\/laminas\/laminas-ldap\/zipball\/649fae8982149b93071c4a7d56f2c4efeed51aa8","reference":"649fae8982
  149b93071c4a7d56f2c4efeed51aa8","shasum":""},"require":{"ext-ldap":"*","laminas\/laminas-zendframework-bridge":"^1.0","php":"^5.6 || ^7.0"
  },"replace":{"zendframework\/zend-ldap":"^2.10.1"},"require-dev":{"laminas\/laminas-coding-standard":"~1.0.0","laminas\/laminas-config":"^
  2.5","laminas\/laminas-eventmanager":"^2.6.3 || ^3.0.1","laminas\/laminas-stdlib":"^2.7 || ^3.0","php-mock\/php-mock-phpunit":"^1.1.2 || ^
  2.1.1","phpunit\/phpunit":"^5.7.27 || ^6.5.14 || ^7.5.20"},"suggest":{"laminas\/laminas-eventmanager":"Laminas\\EventManager component"},"
  time":"2020-03-29T13:06:47+00:00","type":"library","extra":{"branch-alias":{"dev-master":"2.10.x-dev","dev-develop":"2.11.x-dev"}},"instal
  lation-source":"dist","autoload":{"psr-4":{"Laminas\\Ldap\\":"src\/"}},"notification-url":"https:\/\/packagist.org\/downloads\/","license"
  :["BSD-3-Clause"],"description":"Provides support for LDAP operations including but not limited to binding, searching and modifying entrie
  s in an LDAP directory","homepage":"https:\/\/laminas.dev","keywords":["laminas","ldap"],"install-path":"..\/laminas\/laminas-ldap"},{"nam
  e":"laminas\/laminas-zendframework-bridge","version":"1.1.1","version_normalized":"1.1.1.0","source":{"type":"git","url":"https:\/\/github
  .com\/laminas\/laminas-zendframework-bridge.git","reference":"6ede70583e101030bcace4dcddd648f760ddf642"},"dist":{"type":"zip","url":"https
  :\/\/api.github.com\/repos\/laminas\/laminas-zendframework-bridge\/zipball\/6ede70583e101030bcace4dcddd648f760ddf642","reference":"6ede705
  83e101030bcace4dcddd648f760ddf642","shasum":""},"require":{"php":"^5.6 || ^7.0 || ^8.0"},"require-dev":{"phpunit\/phpunit":"^5.7 || ^6.5 |
  | ^7.5 || ^8.1 || ^9.3","squizlabs\/php_codesniffer":"^3.5"},"time":"2020-09-14T14:23:00+00:00","type":"library","extra":{"laminas":{"modu
  le":"Laminas\\ZendFrameworkBridge"}},"installation-source":"dist","autoload":{"files":["src\/autoload.php"],"psr-4":{"Laminas\\ZendFramewo
  rkBridge\\":"src\/\/"}},"notification-url":"https:\/\/packagist.org\/downloads\/","license":["BSD-3-Clause"],"description":"Alias legacy Z
  F class names to Laminas Project equivalents.","keywords":["ZendFramework","autoloading","laminas","zf"],"funding":[{"url":"https:\/\/fund
  ing.communitybridge.org\/projects\/laminas-project","type":"community_bridge"}],"install-path":"..\/laminas\/laminas-zendframework-bridge"
  }]).
