### ISSUE TITLE
Laminas-ldap version needs to be updated for PHP 8.1

### ISSUE THREAD

**Issue by segedy** [biblibre/omeka-s-module-Ldap#13]
We're testing our Omeka-S instance with Omeka 4.0.1 and PHP 8.1 and running into problems with the Laminas-ldap component in this module. The laminas code has been updated to remove the deprecation problem, so the dependency here needs to be updated from tag 2.10.3 to the current tag (currently 2.17.0). Is it possible to get a quick update for PHP 8.1 compatibility?

https://github.com/biblibre/omeka-s-module-Ldap/blob/641060faa922404a510c88ebf17c936fdc5ec54c/composer.lock#L11

**Comment by jajm** [comment]
Hi,
I don't want to drop support for PHP 7.4 yet, so I'll upgrade laminas-ldap to 2.15.0 which supports PHP 7.4 - 8.1

**Comment by jajm** [comment]
Fixed in [release 0.5.0](https://github.com/biblibre/omeka-s-module-Ldap/releases/tag/v0.5.0)

**Comment by segedy** [comment]
Thanks for the quick update!
