### ISSUE TITLE
Omeka S Not using Plugin

### ISSUE THREAD

**Issue by countremy** [biblibre/omeka-s-module-Ldap#4]
I have the plugin activated but omeka S version 3.1.0 does not use the plugin when authenticating.  It uses the form included with this ldap module but not the ldap adapater for authentication.  Is there a way to for the use of the module or was there a change in Omeka S that makes the plugin not work?

**Comment by countremy** [comment]
Please disregard.  The problem was a conflicting Omeka S Module

**Comment by jajm** [comment]
Can you tell us which one ? Maybe we can do something about it.

**Comment by countremy** [comment]
Yes,  the Module is Called Neatline.  I don't know if it is maintained but I was able to download version 0.3.0 and that is where the problems started.
