### ISSUE TITLE
Undefined Constant

### ISSUE THREAD

**Issue by mufticsanjin** [biblibre/omeka-s-module-Ldap#5]
We are trying to get LDAP module working on your installation of omeka S to talk to our University authentication system. We have followed the instructions for the installation, got the php extension installed and can communicate with it from the command line. We have also set up our local.config.php. However when logging in we can see the following error in the log:

`2022-02-11T13:50:22+00:00` ERR (3): Error: Undefined constant "Ldap\Authentication\Adapter\identity" in /var/www/html/omeka-s/modules/Ldap/src/Authentication/Adapter/LdapAdapter.php:75

Stack trace:
#0 /var/www/html/omeka-s/vendor/laminas/laminas-authentication/src/AuthenticationService.php(111): Ldap\Authentication\Adapter\LdapAdapter->authenticate()
#1 /var/www/html/omeka-s/application/src/Controller/LoginController.php(54): Laminas\Authentication\AuthenticationService->authenticate()
#2 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\LoginController->loginAction()
#3 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#4 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#5 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#6 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#7 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#8 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#9 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#10 /var/www/html/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#11 {main}`

We are not sure if it is something we have not set up properly or if it might be some kind of bug?
We would really appreciate your assistance,

Sanjin

**Comment by zkapfumvuti** [comment]
JFlatness from Omeka-S has indicated there could be a bug in the module.

**Comment by jajm** [comment]
It was indeed a bug, thanks for the bug report!
It is fixed in the master branch
