### ISSUE TITLE
Can security group be included in LDAP servers configuration

### ISSUE THREAD

**Issue by zkapfumvuti** [biblibre/omeka-s-module-Ldap#6]
Hi All,

I'm having issues with limiting user access to my security group in AD.

I have observed that the LDAP servers configuration does not allow the addition of code to facilitate a security group to be configured as the search container.

This will greatly assist in limiting access to certain users within our OU.

**Comment by zkapfumvuti** [comment]
@jajm when you have a moment, may you kindly provide some insight?

**Comment by jajm** [comment]
Hi,

I'm not familiar with AD and security groups. What should be modified in the module to allow that ?

Have you seen all the options on https://docs.laminas.dev/laminas-authentication/adapter/ldap/ ? None of them does what you need ?

**Comment by zkapfumvuti** [comment]
@jajm its working now, I used this format to locate my security group;

'accountFilterFormat' => '(&(sAMAccountName=%s)(memberOf=CN=securitygroup,OU=bigsecurity,OU=Groups,OU=myorg,DC=org,DC=my))',
