### ISSUE TITLE
Merge user profiles created locally and those created using ldap module

### ISSUE THREAD

**Issue by zkapfumvuti** [biblibre/omeka-s-module-Ldap#7]
Hi Team,

I would like to inquire on how to merge users profiles created locally within Omeka-S admin page and those created dynamically using the biblibre module https://github.com/biblibre/omeka-s-module-Ldap

This is so my existing users do not lose their created sites once they dynamically login with their LDAP credentials

**Comment by jajm** [comment]
If the module setting "LDAP attribute to use as user email" is set, and if local users have the same email as their corresponding LDAP account, local account should be "linked" to LDAP account on first login. So logging in locally or with LDAP will authenticate you as the same Omeka S user account.

**Comment by zkapfumvuti** [comment]
<img width="1026" alt="Screenshot 2022-04-13 at 13 56 43" src="https://user-images.githubusercontent.com/60696384/163174973-abd75420-d8f6-465f-a33f-624bab36c732.png">

Are these settings correct?

**Comment by jajm** [comment]
It depends on your LDAP server configuration. Do users created by an LDAP login have their email and name correctly set ? If yes, the settings are correct.

**Comment by zkapfumvuti** [comment]
Ok thanks @jajm, that confirms it.
