### ISSUE TITLE
Issue installing module on Omeka-S 3.2.0

### ISSUE THREAD

**Issue by zkapfumvuti** [biblibre/omeka-s-module-Ldap#8]
Hi all,

I'm having an issue with installing the LDAP module on Omeka-S version 3.2.0.

It's on PHP version 8.1 and Ubuntu 18.

Once I complete enabling the module on the backend, when I go to the admin section in Omeka-S and click install, it crashes my entire Omeka-S website.

I get an .500 error page.

**Comment by jajm** [comment]
I installed a fresh Omeka S 3.2.0 on Debian testing (PHP 8.1), and when enabling Ldap module I also got a 500 error page. But I think it's not related to this module. If I disable it, the problem remains.

I believe Omeka S 3.2.0 is not fully compatible with PHP 8.1, as there was several commits pushed recently in branch `develop` related to PHP 8.1. And if I switch to the `develop` branch. There is no problem with the module

**Comment by zkapfumvuti** [comment]
Ok thanks for troubleshooting, should we rather use PHP 8.0?

**Comment by jajm** [comment]
> Ok thanks for troubleshooting, should we rather use PHP 8.0?

That's what I'd do

**Comment by zkapfumvuti** [comment]
Ok thanks once again
