### ISSUE TITLE
LDAP module installation on Omeka S 3.2.0

### ISSUE THREAD

**Issue by hklish01** [biblibre/omeka-s-module-Ldap#9]
Hi,

I'm having an issue with installing the LDAP module on Omeka-S version 0.3.2.

We're on PHP 7.4.26 on RedHat 8.5.

After I install the module, I get a 500 error in my browser when I navigate to our Omeka instance.  The only way to fix this is to remove the ldap module folder from the modules directory.  However, the module is still installed.  

I've looked through all my logs and there's nothing in the logs.

I would appreciate some help with this.

**Comment by jajm** [comment]
Hi,

Have you looked inside Apache logs too ?

What are the other enabled modules ?

**Comment by hklish01** [comment]
There are no other enabled modules.  It's a fresh install of Omeka S.  Just to clarify Omeka is v.3.2.0 and the LDAP module is 0.3.2.

I looked at both the PHP/Apache error logs and nothing is appearing.  These are the last three lines of our access log.  FYI: I've obscured the URL - the UI is only available on campus anyway.

[11/May/2022:11:43:42 -0400] "GET /admin/module HTTP/1.1" 200 2504 "https://xxxxx.tufts.edu/admin/user"
[11/May/2022:11:44:37 -0400] "POST /admin/module/install?id=Ldap HTTP/1.1" 302 - "https://xxxxxx.tufts.edu/admin/module"
[11/May/2022:11:44:38 -0400] "GET /admin/module/configure?id=Ldap HTTP/1.1" 500 - "https:/xxxxx.tufts.edu/admin/module"

**Comment by jajm** [comment]
Did you execute `composer install --no-dev` inside the Ldap repertory ?

**Comment by hklish01** [comment]
No, I used the zip file and installed from the UI.

**Comment by jajm** [comment]
That's what I thought. The zip file for 0.3.2 was missing some files (the `vendor` directory). I fixed that.
Please try to re-download https://github.com/biblibre/omeka-s-module-Ldap/releases/download/v0.3.2/Ldap-0.3.2.zip and reinstall it.

**Comment by hklish01** [comment]
Thanks!  I got it this new version installed and I was able to get LDAP authentication working.

I appreciate your help.
